### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [amt911/zsh-mgr#21]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by amt911** [comment]
Hello.

I have now added the license to the project. If you have any other issues please let me know.

Thank you for checking out my project!
